### ISSUE TITLE
move taw_viewdistance to a mod

### ISSUE THREAD

**Issue by freghar** [CntoDev/template#1]
cnto-mmt-repo includes TAW_viewdistance as a mission-level script - this unnecessarily increases the mission size/complexity as it doesn't change between missions - it should be moved to a mod (like the [upstream page](http://www.armaholic.com/page.php?id=22283) suggests).

This (new) template doesn't include it yet, but to match the functionality of cnto-mmt-repo, this will need to be somehow resolved.

**Comment by freghar** [comment]
As mentioned in CntoDev/cnto-mmt-repo#65 and CntoDev/cnto-mmt-repo#72, the reason for the script/mission version was so that both Coop and PvP missions could use the same modset.

This can still be the case, we just need a global variable to configure the TAW mod to not allow disabling grass on the PvP template, which seems to be upstream functionality already:

> For Mission Makers:
> If you want to disable the grass Option 'None' just set in your missions init.sqf: tawvd_disablenone = true; and the grass option 'None' can't be used by the addon version or if you would just want to disable it for that specific mission you can set the following variable in your init.sqf: tawvd_addon_disable = true; and no one will be able to use this addon on that mission.

As far as people using modified versions and cheating that way - putting TAW in a mission script won't prevent that in any way.

**Comment by Abuk007** [comment]
If the idea is to make our approach template less and go with compositions then we need 2 separate compositions for coop and pvp to implement this. For time of using templates this shouldn't be a large issue, even while possible to cheat it requires that one does know specifically how to do it and does it intentionally which shouldn't occur in our community.

**Comment by freghar** [comment]
> we need 2 separate compositions for coop and pvp to implement this

We don't - we just export one of the global variables (as we will already have at least three template versions), similarly how we now modify MCC to not allow grass disablement. We can either disable TAW on the PvP template or just disable the "Grass = None" option.

The reason isn't that we couldn't do it via template versions alone (excluding TAW as a mission script on PvP), but that it doesn't belong there - it should be a client-side mod.
IOW - We can achieve the same functionality we currently have (eg. no TAW on PvP) just with a simple global variable exported by the PvP template.

**Comment by Abuk007** [comment]
Can compositions attach .sqf files? I'm asking from missionmaking point of
view how one would define if a mission is coop or pvp (thus having
different global variables set).
30 mar 2016 12:29 "freghar" notifications@github.com napisał(a):

**Comment by freghar** [comment]
@Abuk007 This has absolutely nothing to do with compositions. This template isn't a final product to be used for missions, there will be "variations" (as mentioned), ie. for Training, Coop and PvP, each with its own enabled template features (see `userconfig.h`), potentially custom mission load screen image, etc. And within these customizations, we can easily define another global variable in `init.sqf` for disabling TAW, disabling grass setting for MCC, etc.
