### ISSUE TITLE
rework faction-based loadouts, add one XEH per class

### ISSUE THREAD

**Issue by freghar** [CntoDev/template#12]

**Comment by milivojm** [comment]
One question. If I understand correctly, there is no need to have both 

FEAT_CUSTOM_FACTIONS and FEAT_ARSENAL_RESPAWN turned on at the same time?

**Comment by freghar** [comment]
No, I never really tested both, they would probably be kind of conflicting. We can't really specify the execution order - it depends on whether the Arsenal engine gear load happens before/after XEH init + whether `onPlayerRespawn.sqf` is executed before/after XEH respawn.

TL;DR - they are mutually exclusive.

**Comment by milivojm** [comment]
Ok, thanks.
