### ISSUE TITLE
add weapon pool autosave function

### ISSUE THREAD

**Issue by freghar** [CntoDev/template#25]
The Weapon Pool feature,

https://community.bistudio.com/wiki/Category:Command_Group:_Weapon_Pool
https://youtu.be/SpJCgpi7hEg

can be used for customization of loadouts (on the briefing screen) by the player. This plays nicely with Custom_Factions as class-based loadouts are initialized before that (when opening the briefing map screen). This new function would then `waitUntil { time > 0 };` and save the loadout into a client-local variable. At the same time, it would save the loadout pool in a Cargo object type (box, car, etc.) and add a Respawn EH on the player, adding a one-use "Restore loadout" action on the box.

This is to prevent any race conditions with class-based loadouts (the action would be activated after) and makes this an opt-in for the player.

JIP-ed players would get a one-time "Save loadout" as they don't get the briefing screen.

This feature could be useful for anything from heavily customized loadout (some playstyles?) to little modifications (changing M16 for M4, adding 1x scope, reorganizing inventory to one's own self-image, etc. - depending on what's in the weapon pool, as set by the mission's `description.ext`).

**Comment by freghar** [comment]
Unfortunately, the "Inventory" thing during briefing was disabled for multiplayer in Arma 3. The pool functionality works, but one would have to manage it via scripts and there's no real use case for it in single missions.

So I just did the manual on-crate (or any object) save/load approach I wanted for JIP players, in 839da8cdb7e16.

**Comment by Abuk007** [comment]
Too bad. Looked promising but also its not really intuitive interface-wise for player to dig there.

**Comment by freghar** [comment]
We can still use the save/load functionality in mission, just not the briefing-time access to it.
